#!/usr/bin/env python
if __name__=="__main__":
    import sys
    from pathlib import Path

    sys.path.insert(0,str(Path(__file__).parent))

    import archaeal_module.__main__

    archaeal_module.__main__.main()
